window.FREE_RESOURCES = [
  {
    id: 'f-def-1',
    role: 'DEFENSE',
    cat: 'labs',
    icon: '🛡️',
    title: 'LetsDefend — Community SOC Simulator',
    desc: 'Hands-on practical blue team training platform. Investigate realistic SOC alerts, analyze malicious phishing emails, and triage malware infections in a sandboxed SIEM.',
    url: 'https://letsdefend.io/',
    free: true,
    type: 'Interactive SOC Lab',
    badge: 'Beginner to Intermediate'
  },
  {
    id: 'f-def-2',
    role: 'DEFENSE',
    cat: 'labs',
    icon: '🧪',
    title: 'CyberDefenders — Blue Team Cyber Ranges',
    desc: 'Practice real-world incident response and digital forensics using Wireshark, Volatility, Splunk, Zeek, and FTK Imager against actual packet captures and disk dumps.',
    url: 'https://cyberdefenders.org/',
    free: true,
    type: 'Digital Forensics Lab',
    badge: 'Hands-On Investigation'
  },
  {
    id: 'f-def-3',
    role: 'DEFENSE',
    cat: 'labs',
    icon: '🔍',
    title: 'Blue Team Labs Online (BTLO)',
    desc: 'Gamified defensive cybersecurity challenges. Solve investigations covering Security Operations, Digital Forensics, Incident Response, and Threat Hunting.',
    url: 'https://blueteamlabs.online/',
    free: true,
    type: 'Blue Team Challenges',
    badge: 'Industry Practice'
  },
  {
    id: 'f-def-4',
    role: 'DEFENSE',
    cat: 'labs',
    icon: '📊',
    title: 'Splunk Boss of the SOC (BOTS) Datasets',
    desc: 'Free downloadable investigation datasets used in official Splunk competitions. Practice hunting APT attacks, credential stuffing, and web exploits using real enterprise logs.',
    url: 'https://github.com/splunk/botsv3',
    free: true,
    type: 'SIEM Log Dataset',
    badge: 'Splunk Enterprise'
  },
  {
    id: 'f-def-5',
    role: 'DEFENSE',
    cat: 'books',
    icon: '🧭',
    title: 'MITRE ATT&CK Matrix & Navigator',
    desc: 'The global knowledge base of adversary tactics and techniques based on real-world observations. Essential for mapping detections and threat intelligence.',
    url: 'https://attack.mitre.org/',
    free: true,
    type: 'Threat Matrix Framework',
    badge: 'Standard Framework'
  },
  {
    id: 'f-def-6',
    role: 'DEFENSE',
    cat: 'books',
    icon: '📜',
    title: 'SigmaHQ — Universal Detection Rules',
    desc: 'Open signature format for SIEM systems. Learn how top detection engineers write generic detection rules that translate directly to Splunk, Elastic, and Sentinel.',
    url: 'https://github.com/SigmaHQ/sigma',
    free: true,
    type: 'Detection Engineering',
    badge: 'Open Source'
  },
  {
    id: 'f-def-7',
    role: 'DEFENSE',
    cat: 'youtube',
    icon: '📺',
    title: 'John Hammond — Threat Analysis & CTFs',
    desc: 'World-class walkthroughs of malware reverse engineering, log analysis, threat actor TTPs, and deep forensic breakdowns.',
    url: 'https://www.youtube.com/@_JohnHammond',
    free: true,
    type: 'YouTube Channel',
    badge: 'Top Defensive Channel'
  },
  {
    id: 'f-def-8',
    role: 'DEFENSE',
    cat: 'youtube',
    icon: '📺',
    title: 'Professor Messer — CompTIA Security+ & Net+',
    desc: 'Full-length, high-production video training courses for CompTIA Security+ SY0-701 and Network+ N10-009, 100% free with no paywall.',
    url: 'https://www.youtube.com/@professormesser',
    free: true,
    type: 'Certification Training',
    badge: 'CompTIA Free Course'
  },
  {
    id: 'f-def-9',
    role: 'DEFENSE',
    cat: 'audio',
    icon: '🎧',
    title: 'SANS Internet Storm Center Daily Stormcast',
    desc: 'A daily 5-minute concise briefing on current cyber threats, zero-days, active network attacks, and indicators of compromise from Dr. Johannes Ullrich.',
    url: 'https://isc.sans.edu/podcast.html',
    free: true,
    type: 'Daily Security Briefing',
    badge: 'Threat Intel Daily'
  },

  {
    id: 'f-off-1',
    role: 'OFFENSIVE',
    cat: 'labs',
    icon: '🎯',
    title: 'PortSwigger Web Security Academy',
    desc: 'Completely free interactive web security training with live vulnerable labs covering SQLi, XSS, CSRF, SSRF, XXE, JWT, OAuth, Race Conditions, and Business Logic flaws.',
    url: 'https://portswigger.net/web-security',
    free: true,
    type: 'Web Pentest Academy',
    badge: 'Gold Standard Labs'
  },
  {
    id: 'f-off-2',
    role: 'OFFENSIVE',
    cat: 'labs',
    icon: '⚔️',
    title: 'Hack The Box Academy (Tier 0 Free)',
    desc: 'Modular, hands-on offensive training modules with interactive in-browser targets covering Linux fundamentals, Windows command line, and web request exploitation.',
    url: 'https://academy.hackthebox.com/',
    free: true,
    type: 'Hands-on Academy',
    badge: 'Free Tier Available'
  },
  {
    id: 'f-off-3',
    role: 'OFFENSIVE',
    cat: 'labs',
    icon: '🏰',
    title: 'OverTheWire Wargames: Bandit to Natas',
    desc: 'Gamified Linux and web exploitation challenges designed for beginners and intermediate hackers. Master SSH, Bash, file permissions, and cryptographic puzzles.',
    url: 'https://overthewire.org/wargames/',
    free: true,
    type: 'Interactive Wargame',
    badge: 'Command-Line Mastery'
  },
  {
    id: 'f-off-4',
    role: 'OFFENSIVE',
    cat: 'labs',
    icon: '🧃',
    title: 'OWASP Juice Shop',
    desc: 'The most modern and sophisticated intentionally vulnerable web application. Covers all OWASP Top 10 vulnerabilities with automated score tracking and CTF integration.',
    url: 'https://owasp.org/www-project-juice-shop/',
    free: true,
    type: 'Vulnerable Web App',
    badge: 'Self-Hosted Lab'
  },
  {
    id: 'f-off-5',
    role: 'OFFENSIVE',
    cat: 'books',
    icon: '📖',
    title: 'HackTricks & Cloud Pentest Wiki',
    desc: 'The world\'s most comprehensive ethical hacking methodology encyclopedia. Features thousands of commands, payload recipes, privilege escalation vectors, and evasion tricks.',
    url: 'https://book.hacktricks.xyz/',
    free: true,
    type: 'Pentest Methodology',
    badge: 'Exhaustive Wiki'
  },
  {
    id: 'f-off-6',
    role: 'OFFENSIVE',
    cat: 'books',
    icon: '🧰',
    title: 'PayloadsAllTheThings Repository',
    desc: 'A massive GitHub collection of useful payloads and bypasses for web application security and red teaming. Ideal for quick reference during lab challenges.',
    url: 'https://github.com/swisskyrepo/PayloadsAllTheThings',
    free: true,
    type: 'Exploit Payloads',
    badge: 'GitHub Open Source'
  },
  {
    id: 'f-off-7',
    role: 'OFFENSIVE',
    cat: 'youtube',
    icon: '📺',
    title: 'TCM Security (The Cyber Mentor)',
    desc: 'Practical ethical hacking, practical network penetration testing (PNPT) walkthroughs, Active Directory attacks, and OSCP preparation guidance.',
    url: 'https://www.youtube.com/@TCMSecurityAcademy',
    free: true,
    type: 'Ethical Hacking Tutorials',
    badge: 'Practical Red Team'
  },
  {
    id: 'f-off-8',
    role: 'OFFENSIVE',
    cat: 'youtube',
    icon: '📺',
    title: 'IppSec — HTB Machine Walkthroughs',
    desc: 'Methodical, deeply technical video walkthroughs solving Hack The Box machines. The quintessential study material for developing real offensive problem-solving skills.',
    url: 'https://www.youtube.com/@ippsec',
    free: true,
    type: 'Machine Walkthroughs',
    badge: 'Advanced Methodology'
  },

  {
    id: 'f-eng-1',
    role: 'ENGINEERING',
    cat: 'labs',
    icon: '☁️',
    title: 'flAWS.cloud & flAWS2.cloud (AWS CTF)',
    desc: 'The classic hands-on AWS misconfiguration security challenge. Learn how IAM privilege escalation, S3 permissions, and EC2 instance metadata exploits work in real life.',
    url: 'http://flaws.cloud/',
    free: true,
    type: 'Cloud CTF Range',
    badge: 'AWS Security'
  },
  {
    id: 'f-eng-2',
    role: 'ENGINEERING',
    cat: 'labs',
    icon: '🐐',
    title: 'CloudGoat (Rhino Security Labs)',
    desc: 'Vulnerable-by-design AWS deployment tool via Terraform. Run 14+ realistic multi-stage cloud attack scenarios on your own AWS free tier account.',
    url: 'https://github.com/RhinoSecurityLabs/cloudgoat',
    free: true,
    type: 'Terraform Cloud Lab',
    badge: 'Multi-Stage Scenarios'
  },
  {
    id: 'f-eng-3',
    role: 'ENGINEERING',
    cat: 'labs',
    icon: '⚓',
    title: 'Wiz EKS Cluster Games',
    desc: 'Interactive Kubernetes security CTF by Wiz. Solve hands-on container breakout scenarios, discover Pod IAM roles, and exploit insecure RBAC configurations.',
    url: 'https://eksclustergames.com/',
    free: true,
    type: 'Kubernetes CTF',
    badge: 'Container Security'
  },
  {
    id: 'f-eng-4',
    role: 'ENGINEERING',
    cat: 'labs',
    icon: '🔑',
    title: 'Wiz Big IAM Challenge',
    desc: 'Challenge-based lab focused purely on AWS IAM privilege escalation, trust relationship flaws, assumed role misuse, and cross-account bucket policies.',
    url: 'https://bigiamchallenge.com/',
    free: true,
    type: 'IAM Security CTF',
    badge: 'Cloud IAM Focus'
  },
  {
    id: 'f-eng-5',
    role: 'ENGINEERING',
    cat: 'books',
    icon: '🛡️',
    title: 'OWASP Application Security Verification Standard (ASVS)',
    desc: 'The industry framework for defining security requirements and architecture controls for modern web applications and APIs during development.',
    url: 'https://owasp.org/www-project-application-security-verification-standard/',
    free: true,
    type: 'AppSec Architecture',
    badge: 'Engineering Standard'
  },
  {
    id: 'f-eng-6',
    role: 'ENGINEERING',
    cat: 'books',
    icon: '📚',
    title: 'AWS Well-Architected Framework: Security Pillar',
    desc: 'Official architectural guidance from AWS engineers covering identity management, incident response, infrastructure protection, and automated guardrails.',
    url: 'https://docs.aws.amazon.com/wellarchitected/latest/security-pillar/welcome.html',
    free: true,
    type: 'Architecture Whitepaper',
    badge: 'AWS Official'
  },
  {
    id: 'f-eng-7',
    role: 'ENGINEERING',
    cat: 'youtube',
    icon: '📺',
    title: 'TechWorld with Nana — DevOps & Containers',
    desc: 'World-renowned explanations of Docker, Kubernetes, Terraform, Helm, Prometheus, and CI/CD security pipelines. Highly visual and easy to follow.',
    url: 'https://www.youtube.com/@techworld_with_nana',
    free: true,
    type: 'DevOps & Cloud',
    badge: 'Top Educator'
  },
  {
    id: 'f-eng-8',
    role: 'ENGINEERING',
    cat: 'youtube',
    icon: '📺',
    title: 'Abhishek Veeramalla — DevSecOps Zero to Hero',
    desc: 'Hands-on practical video series building full DevSecOps CI/CD pipelines integrating Trivy, SonarQube, OWASP Dependency-Check, and ArgoCD on AWS.',
    url: 'https://www.youtube.com/@AbhishekVeeramalla',
    free: true,
    type: 'DevSecOps Projects',
    badge: 'Hands-On Projects'
  },

  {
    id: 'f-grc-1',
    role: 'GRC',
    cat: 'books',
    icon: '🏛️',
    title: 'NIST Cybersecurity Framework 2.0 (CSF 2.0)',
    desc: 'The newly released 2024 update to the world\'s most adopted cybersecurity framework. Learn the 6 core functions: Govern, Identify, Protect, Detect, Respond, and Recover.',
    url: 'https://www.nist.gov/cyberframework',
    free: true,
    type: 'Federal Framework',
    badge: 'Global Benchmark'
  },
  {
    id: 'f-grc-2',
    role: 'GRC',
    cat: 'books',
    icon: '📑',
    title: 'NIST SP 800-53 Rev 5 Control Explorer',
    desc: 'The catalog of security and privacy controls for federal information systems. The baseline reference behind FedRAMP, FISMA, and DoD authorization to operate (ATO).',
    url: 'https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final',
    free: true,
    type: 'Security Controls Catalog',
    badge: 'Enterprise Compliance'
  },
  {
    id: 'f-grc-3',
    role: 'GRC',
    cat: 'books',
    icon: '⚙️',
    title: 'CIS Critical Security Controls v8',
    desc: 'The prioritized set of 18 critical security actions that protect organizations and data from known cyber attack vectors. Includes mapping to ISO and NIST.',
    url: 'https://www.cisecurity.org/controls',
    free: true,
    type: 'Prioritized Defense',
    badge: 'CIS Baseline'
  },
  {
    id: 'f-grc-4',
    role: 'GRC',
    cat: 'books',
    icon: '☁️',
    title: 'Cloud Security Alliance (CSA) Security Guidance v5',
    desc: 'Comprehensive guidance spanning 12 cloud security domains including cloud risk governance, legal issues, data security, encryption, and supply chain management.',
    url: 'https://cloudsecurityalliance.org/research/guidance/',
    free: true,
    type: 'Cloud Governance',
    badge: 'CSA Standard'
  },
  {
    id: 'f-grc-5',
    role: 'GRC',
    cat: 'youtube',
    icon: '📺',
    title: 'Simply Cyber (Dr. Gerald Auger)',
    desc: 'Daily live shows, GRC masterclasses, risk assessment walkthroughs, and career coaching for aspiring compliance analysts, auditors, and CISOs.',
    url: 'https://www.youtube.com/@SimplyCyber',
    free: true,
    type: 'GRC Career Mentorship',
    badge: 'Community Favorite'
  },
  {
    id: 'f-grc-6',
    role: 'GRC',
    cat: 'courses',
    icon: '🎓',
    title: 'CISA Cybersecurity Governance Training',
    desc: 'Free federal courses provided by the U.S. Cybersecurity and Infrastructure Security Agency on risk assessment methodology and operational resilience.',
    url: 'https://www.cisa.gov/cybersecurity-training-exercises',
    free: true,
    type: 'Government Training',
    badge: 'Official CISA'
  },

  {
    id: 'f-ai-1',
    role: 'AI_SECURITY',
    cat: 'books',
    icon: '🤖',
    title: 'OWASP Top 10 for Large Language Model (LLM) Apps',
    desc: 'The definitive standard for AI security risks: Prompt Injection, Insecure Output Handling, Training Data Poisoning, Model Denial of Service, and Supply Chain Vulnerabilities.',
    url: 'https://owasp.org/www-project-top-10-for-large-language-model-applications/',
    free: true,
    type: 'AI Vulnerability Standard',
    badge: 'Must-Read 2026'
  },
  {
    id: 'f-ai-2',
    role: 'AI_SECURITY',
    cat: 'books',
    icon: '🗺️',
    title: 'MITRE ATLAS (Adversarial Threat Landscape in AI)',
    desc: 'Knowledge base of adversary tactics, techniques, and case studies targeting machine learning systems, modeled after the world-famous MITRE ATT&CK matrix.',
    url: 'https://atlas.mitre.org/',
    free: true,
    type: 'Adversarial ML Framework',
    badge: 'MITRE Standard'
  },
  {
    id: 'f-ai-3',
    role: 'AI_SECURITY',
    cat: 'labs',
    icon: '🧙‍♂️',
    title: 'Lakera Gandalf — Prompt Injection Game',
    desc: 'Can you trick the AI wizard into revealing his password? Test your prompt injection, jailbreaking, and defensive filtering skills across 8 escalating defense levels.',
    url: 'https://gandalf.lakera.ai/',
    free: true,
    type: 'Interactive AI Sandbox',
    badge: 'Gamified AI Defense'
  },
  {
    id: 'f-ai-4',
    role: 'AI_SECURITY',
    cat: 'books',
    icon: '⚖️',
    title: 'NIST AI Risk Management Framework (AI RMF 1.0)',
    desc: 'Federal guidance intended for voluntary use to address risks in the design, development, use, and evaluation of AI products, services, and systems.',
    url: 'https://www.nist.gov/itl/ai-risk-management-framework',
    free: true,
    type: 'AI Governance Standard',
    badge: 'NIST Publication'
  },
  {
    id: 'f-ai-5',
    role: 'AI_SECURITY',
    cat: 'books',
    icon: '🛡️',
    title: 'Google Secure AI Framework (SAIF)',
    desc: 'Google\'s conceptual approach to securing AI systems: expanding strong security foundations, automated defenses, and continuous red teaming for frontier models.',
    url: 'https://safety.google/cybersecurity-advancements/saif/',
    free: true,
    type: 'Industry Architecture',
    badge: 'Google Engineering'
  },
  {
    id: 'f-ai-6',
    role: 'AI_SECURITY',
    cat: 'courses',
    icon: '🎓',
    title: 'DeepLearning.AI: Prompt Engineering & AI Safety',
    desc: 'Short courses by Andrew Ng and industry leaders on prompt engineering, evaluating LLM guardrails, and building robust, resilient AI agents.',
    url: 'https://www.deeplearning.ai/short-courses/',
    free: true,
    type: 'Interactive Courses',
    badge: 'AI Fundamentals'
  }
];

window.PAID_RESOURCES = [
  {
    id: 'p-def-1',
    role: 'DEFENSE',
    roleName: 'Cyber Defense & SOC',
    cat: 'cert',
    name: 'SANS SEC504: Hacker Tools, Techniques & Incident Handling (GIAC GCIH)',
    provider: 'SANS Institute & GIAC',
    pricingTier: '$$$$',
    priceEstimate: '~$8,900 USD',
    categoryName: 'Immersive Bootcamp & Certification',
    description: 'The global enterprise standard for incident responders and SOC team leads. Master dynamic malware analysis, live triage forensics, network packet reconstruction, and cloud containment.',
    highlights: [
      'Gold standard GIAC GCIH certification recognized worldwide',
      '6 full days of intensive lab-driven technical instruction',
      'Comprehensive cyber range incident challenge on day 6',
      'Eligible for employer training budget / tuition reimbursement'
    ],
    roiScore: '99/100',
    companySponsorshipTip: 'Highlight the immediate reduction in dwell time and incident containment speed for company audit compliance.',
    url: 'https://www.sans.org/cyber-security-courses/hacker-techniques-tools-incident-handling/'
  },
  {
    id: 'p-def-2',
    role: 'DEFENSE',
    roleName: 'Cyber Defense & SOC',
    cat: 'cert',
    name: 'Blue Team Level 1 (BTL1 Certification)',
    provider: 'Security Blue Team',
    pricingTier: '$$',
    priceEstimate: '~£399 (~$520 USD)',
    categoryName: 'Practical 24-Hour Exam',
    description: 'A 100% practical, hands-on defensive certification designed for junior and mid-level SOC analysts. Includes full access to real SIEM, phishing, and forensics labs followed by a 24-hour incident investigation exam.',
    highlights: [
      '24-hour practical incident response exam with real incident report generation',
      'Covers Phishing Analysis, Threat Intel, Digital Forensics, and SIEM',
      'Includes physical challenge coin upon achieving pass with merit',
      'Direct industry recognition across top enterprise SOCs'
    ],
    roiScore: '96/100',
    companySponsorshipTip: 'Very accessible price point under $600 with direct measurable skills testing in enterprise tools.',
    url: 'https://securityblue.team/why-btl1/'
  },
  {
    id: 'p-def-3',
    role: 'DEFENSE',
    roleName: 'Cyber Defense & SOC',
    cat: 'platform',
    name: 'LetsDefend VIP Pro SOC Analyst Pass',
    provider: 'LetsDefend',
    pricingTier: '$',
    priceEstimate: '$19.99/mo or $199/yr',
    categoryName: 'Continuous Cloud Range Subscription',
    description: 'A dedicated simulated SOC environment where you receive real security alerts, examine host logs, analyze sandbox outputs, perform endpoint isolation, and complete case tickets.',
    highlights: [
      '500+ realistic simulated alerts with true/false positive verification',
      'Hands-on EDR (Endpoint Detection & Response) investigation module',
      'Splunk, Elastic, and Wireshark integrated into the browser',
      'Role-based progression tracks for SOC Tier 1, 2, and DFIR'
    ],
    roiScore: '95/100',
    companySponsorshipTip: 'Low monthly cost ideal for departmental learning and development expense cards.',
    url: 'https://letsdefend.io/pricing'
  },
  {
    id: 'p-def-4',
    role: 'DEFENSE',
    roleName: 'Cyber Defense & SOC',
    cat: 'platform',
    name: 'CyberDefenders Pro Cyber Range Access',
    provider: 'CyberDefenders',
    pricingTier: '$',
    priceEstimate: '$20/mo or $200/yr',
    categoryName: 'DFIR & Threat Hunting Cyber Range',
    description: 'Unlimited access to advanced enterprise investigation challenges, memory dump analysis (Volatility 3), cloud logs (AWS CloudTrail, Azure Entra ID), and endpoint triage.',
    highlights: [
      'Access to premium BlueYard cyber range scenarios',
      'Full virtual machines pre-loaded with commercial forensics toolkits',
      'Real-world malware PCAP analysis and packet carving',
      'Verified certificates of completion for each solved case'
    ],
    roiScore: '94/100',
    companySponsorshipTip: 'Perfect ongoing skill maintenance tool for active security operation center staff.',
    url: 'https://cyberdefenders.org/pricing/'
  },
  {
    id: 'p-def-5',
    role: 'DEFENSE',
    roleName: 'Cyber Defense & SOC',
    cat: 'course',
    name: 'Splunk Enterprise Certified Administrator & Power User',
    provider: 'Splunk Training',
    pricingTier: '$$$',
    priceEstimate: '$1,500 – $2,500 USD',
    categoryName: 'Vendor Certification Track',
    description: 'Official enterprise training program teaching Splunk cluster deployment, data forwarding pipelines, distributed search, SPL query optimization, and enterprise dashboard architecture.',
    highlights: [
      'Official Splunk credential required by major MSSPs and government contractors',
      'Master data ingestion, parsing, indexing, and pipeline routing',
      'Build automated alert triggers and correlation searches',
      'Significant salary multiplier in the SOC engineering market'
    ],
    roiScore: '93/100',
    companySponsorshipTip: 'Crucial for any company currently paying for enterprise Splunk licenses.',
    url: 'https://www.splunk.com/en_us/training.html'
  },
  {
    id: 'p-def-6',
    role: 'DEFENSE',
    roleName: 'Cyber Defense & SOC',
    cat: 'cert',
    name: 'CompTIA Security+ (SY0-701) Official Exam Voucher',
    provider: 'CompTIA Official Store',
    pricingTier: '$$',
    priceEstimate: '$404 USD',
    categoryName: 'Foundational Industry Benchmark',
    description: 'The global standard foundational security credential meeting ISO 17024 and DoD 8140/8570 compliance. Validates baseline enterprise security, network architecture, and security operations.',
    highlights: [
      'Official CompTIA voucher with 12 months testing eligibility via Pearson VUE',
      'Covers General Security Concepts, Threats, Vulnerabilities, Architecture & Operations',
      'Universally requested prerequisite for entry-level SOC and security analyst positions',
      'Qualifies for corporate training reimbursement across all major enterprise sectors'
    ],
    roiScore: '98/100',
    companySponsorshipTip: 'Universally accepted corporate training item for onboarding IT staff into security.',
    url: 'https://store.comptia.org/comptia-security-plus-voucher/p/SEC-701-TSTV-20-C'
  },
  {
    id: 'p-def-7',
    role: 'DEFENSE',
    roleName: 'Cyber Defense & SOC',
    cat: 'cert',
    name: 'CompTIA CySA+ (Cybersecurity Analyst CS0-003)',
    provider: 'CompTIA',
    pricingTier: '$$',
    priceEstimate: '$404 USD',
    categoryName: 'Mid-Level SOC Analyst Certification',
    description: 'Applies behavioral analytics to networks and devices to prevent, detect, and combat cybersecurity threats through continuous security monitoring and proactive threat intelligence.',
    highlights: [
      'Performance-based questions testing live log analysis and firewall rules',
      'Maps directly to intermediate SOC Analyst Tier 2 operational duties',
      'Covers Vulnerability Management, SIEM monitoring, and Incident Response',
      'Recognized under US DoD 8570/8140 Directive for Cyber Defense Analysts'
    ],
    roiScore: '95/100',
    companySponsorshipTip: 'Directly validates practical log analysis and response capabilities for SOC team members.',
    url: 'https://www.comptia.org/certifications/cybersecurity-analyst'
  },
  {
    id: 'p-def-8',
    role: 'DEFENSE',
    roleName: 'Cyber Defense & SOC',
    cat: 'platform',
    name: 'TryHackMe SOC Level 1 & 2 Career Path (VIP)',
    provider: 'TryHackMe',
    pricingTier: '$',
    priceEstimate: '$14 / month or $126 / year',
    categoryName: 'Interactive Hands-On Blue Team Range',
    description: 'Full guided hands-on rooms covering cyber defense fundamentals: Wireshark, Splunk, Zeek, Snort, Brim, Volatility, and live incident response scenarios with dedicated cloud VM access.',
    highlights: [
      'Over 80 hours of interactive step-by-step hands-on defensive training',
      'Browser-based virtual machines with real enterprise tooling pre-installed',
      'Earn official verifiable SOC Level 1 and Level 2 completion certificates',
      'Extremely economical subscription that covers daily hands-on practice'
    ],
    roiScore: '96/100',
    companySponsorshipTip: 'Inexpensive ongoing training tool for early-career security specialists.',
    url: 'https://tryhackme.com/path/outline/soclevel1'
  },

  {
    id: 'p-off-1',
    role: 'OFFENSIVE',
    roleName: 'Offensive Security (Red)',
    cat: 'cert',
    name: 'OffSec PEN-200: Penetration Testing with Kali Linux (OSCP)',
    provider: 'Offensive Security (OffSec)',
    pricingTier: '$$$$',
    priceEstimate: '$1,649 – $2,599 USD',
    categoryName: 'Hands-on Exam & Dedicated Cyber Range',
    description: 'The world\'s most renowned penetration testing credential. A gruelling 24-hour practical hacking exam requiring you to compromise network targets, execute Active Directory privilege escalation, and write a full technical report.',
    highlights: [
      'The #1 prerequisite certification listed for commercial penetration testers',
      '90 days of access to dedicated private lab networks',
      'Full Active Directory domain compromise methodology',
      '24-hour proctored practical examination'
    ],
    roiScore: '100/100',
    companySponsorshipTip: 'Widely sponsored by consulting firms and security providers as the baseline technical requirement.',
    url: 'https://www.offsec.com/courses/pen-200/'
  },
  {
    id: 'p-off-2',
    role: 'OFFENSIVE',
    roleName: 'Offensive Security (Red)',
    cat: 'cert',
    name: 'Certified Red Team Operator (CRTO)',
    provider: 'Zero-Point Security',
    pricingTier: '$$',
    priceEstimate: '~£399 (~$520 USD)',
    categoryName: 'Advanced Red Team Exam & Cobalt Strike',
    description: 'Created by prominent red teamer Rastamouse. Master enterprise Active Directory attacks, Kerberos abuse (Kerberoasting, AS-REP roasting), cross-forest trusts, and operational C2 tradecraft with Cobalt Strike.',
    highlights: [
      'Includes dedicated cloud lab access with real Cobalt Strike licenses',
      '48-hour hands-on practical exam across multi-domain forest environments',
      'Teaches modern host and network evasion techniques',
      'Direct bridge between pentesting and advanced red teaming'
    ],
    roiScore: '97/100',
    companySponsorshipTip: 'A fraction of the price of traditional corporate red team training with superior modern AD relevance.',
    url: 'https://training.zeropointsecurity.co.uk/courses/red-team-ops'
  },
  {
    id: 'p-off-3',
    role: 'OFFENSIVE',
    roleName: 'Offensive Security (Red)',
    cat: 'platform',
    name: 'Hack The Box VIP+ & Pro Labs Pass',
    provider: 'Hack The Box',
    pricingTier: '$',
    priceEstimate: '$20 – $49/mo',
    categoryName: 'Dedicated Cyber Range Platform',
    description: 'Skip the queues and access dedicated instance environments. Unlock legendary multi-subnet enterprise Pro Labs (Dante, Offshore, Cybernetics, APT Labs) that simulate full corporate networks.',
    highlights: [
      'Dedicated personal target machines with instant resets',
      'Access to retired machine writeups and official video walkthroughs',
      'Access to multi-forest Pro Labs with realistic lateral movement',
      'Industry-standard CTF and exploitation benchmark'
    ],
    roiScore: '96/100',
    companySponsorshipTip: 'Very low operational cost that can be expensed under personal professional development.',
    url: 'https://www.hackthebox.com/hacker/pro-labs'
  },
  {
    id: 'p-off-4',
    role: 'OFFENSIVE',
    roleName: 'Offensive Security (Red)',
    cat: 'platform',
    name: 'TCM Security All-Access Pass (PNPT Certification)',
    provider: 'TCM Security',
    pricingTier: '$',
    priceEstimate: '$39.99/mo or $299/yr',
    categoryName: 'Course Academy & Practical Exam',
    description: 'Comprehensive offensive security catalog covering Practical Ethical Hacking, OSINT, Linux & Windows Privilege Escalation, Web Application Hacking, and the 5-day PNPT practical exam.',
    highlights: [
      'Over 60+ practical courses taught by seasoned penetration testers',
      'Includes 5-day practical exam simulating an external & internal pentest',
      'Requires a live 15-minute debrief presentation to pass',
      'Unmatched price-to-content value in offensive education'
    ],
    roiScore: '95/100',
    companySponsorshipTip: 'Annual subscription can train an entire junior offensive team for less than one SANS course.',
    url: 'https://tcm-sec.com/all-access-pass/'
  },
  {
    id: 'p-off-5',
    role: 'OFFENSIVE',
    roleName: 'Offensive Security (Red)',
    cat: 'tool',
    name: 'Burp Suite Professional Commercial License',
    provider: 'PortSwigger',
    pricingTier: '$$',
    priceEstimate: '$449 / year',
    categoryName: 'Essential Commercial Software',
    description: 'The mandatory tool in any web pentester or bug bounty hunter\'s arsenal. Includes unlimited scanning rate, Burp Collaborator out-of-band testing, Turbo Intruder, and full BApp Store extension access.',
    highlights: [
      'Automated dynamic vulnerability scanner with false-positive filtering',
      'Burp Collaborator for detecting asynchronous blind SSRF and RCE',
      'Project file saving, search, and session restore capabilities',
      'Essential commercial asset for all Application Security consultants'
    ],
    roiScore: '98/100',
    companySponsorshipTip: 'Standard software purchase order required for every security engineering and pentest team.',
    url: 'https://portswigger.net/burp/pro'
  },
  {
    id: 'p-off-6',
    role: 'OFFENSIVE',
    roleName: 'Offensive Security (Red)',
    cat: 'cert',
    name: 'INE Security eJPT (Junior Penetration Tester Certification)',
    provider: 'INE Security',
    pricingTier: '$$',
    priceEstimate: '$299 USD (Includes Exam + Course)',
    categoryName: 'Hands-On Penetration Testing Benchmark',
    description: 'The premier entry-level practical penetration testing certification. Sits you in a real, multi-host networked corporate environment where you conduct reconnaissance, vulnerability assessments, and web application exploitation.',
    highlights: [
      '100% hands-on dynamic examination with simulated corporate targets',
      'Covers Network Pentesting, Web Application Attacks, and Pivoting',
      'Provides 2 full attempts within the voucher fee',
      'The #1 recommended stepping-stone before attempting OSCP'
    ],
    roiScore: '97/100',
    companySponsorshipTip: 'Affordable, low-risk certification voucher for training junior offensive personnel.',
    url: 'https://ine.com/certifications/ejpt-certification'
  },
  {
    id: 'p-off-7',
    role: 'OFFENSIVE',
    roleName: 'Offensive Security (Red)',
    cat: 'cert',
    name: 'Hack The Box Certified Bug Bounty Hunter (HTB CBBH)',
    provider: 'Hack The Box Academy',
    pricingTier: '$$',
    priceEstimate: '~$210 USD exam + Academy Pass',
    categoryName: 'Web Application Exploitation Certification',
    description: 'A deep-dive practical web application security certification covering advanced SQLi, command injection, SSRF, XSS, deserialization, and IDOR vulnerabilities on live hardened targets.',
    highlights: [
      'Multi-day hands-on examination assessing live enterprise web apps',
      'Complete modular prep on HTB Academy with interactive guided labs',
      'Covers practical exploitation chains and professional vulnerability reporting',
      'Official digital credential issued by Hack The Box'
    ],
    roiScore: '96/100',
    companySponsorshipTip: 'Directly applicable for product security and AppSec engineering roles.',
    url: 'https://academy.hackthebox.com/preview/certifications/htb-certified-bug-bounty-hunter'
  },
  {
    id: 'p-off-8',
    role: 'OFFENSIVE',
    roleName: 'Offensive Security (Red)',
    cat: 'cert',
    name: 'OffSec WEB-300: Advanced Web Attacks & Exploitation (OSWE)',
    provider: 'Offensive Security (OffSec)',
    pricingTier: '$$$$',
    priceEstimate: '$1,649 – $2,599 USD',
    categoryName: 'Elite Whitebox Web Pentesting Certification',
    description: 'The premier whitebox web application pentesting certification. Teaches advanced source code analysis, debugging blackbox binaries, finding complex logic flaws, and writing automated Python exploit scripts.',
    highlights: [
      '48-hour intensive proctored practical whitebox examination',
      'Master PHP, Java, NodeJS, and .NET web application vulnerability discovery',
      'Craft full automated remote code execution exploit chains from scratch',
      'Top-tier credential for senior AppSec engineers and red team researchers'
    ],
    roiScore: '99/100',
    companySponsorshipTip: 'Gold standard corporate sponsorship item for senior application security leads.',
    url: 'https://www.offsec.com/courses/web-300/'
  },

  {
    id: 'p-eng-1',
    role: 'ENGINEERING',
    roleName: 'Security Engineering',
    cat: 'cert',
    name: 'Certified DevSecOps Professional (CDP)',
    provider: 'Practical DevSecOps',
    pricingTier: '$$$',
    priceEstimate: '$699 USD',
    categoryName: 'Hands-On CI/CD Security Certification',
    description: 'Practical certification validating your ability to implement security automation in modern CI/CD pipelines. Learn to embed SAST, DAST, Container Scanning, Secrets Scanning, and IaC verification into GitLab and Jenkins.',
    highlights: [
      '12-hour hands-on practical exam building real security automation pipelines',
      'Master Semgrep, Trivy, OWASP ZAP, and OPA policy-as-code in pipelines',
      'Covers software supply chain security (SBOM, SLSA frameworks)',
      'Highly demanded by Fortune 500 engineering and fintech teams'
    ],
    roiScore: '96/100',
    companySponsorshipTip: 'Directly maps to DevSecOps pipeline initiatives and shift-left engineering mandates.',
    url: 'https://www.practical-devsecops.com/certified-devsecops-professional/'
  },
  {
    id: 'p-eng-2',
    role: 'ENGINEERING',
    roleName: 'Security Engineering',
    cat: 'cert',
    name: 'Certified Kubernetes Security Specialist (CKS)',
    provider: 'Linux Foundation & CNCF',
    pricingTier: '$$',
    priceEstimate: '$395 USD (Includes Killer.sh)',
    categoryName: 'Performance-Based Live Exam',
    description: 'A 2-hour performance exam where you sit in front of real Kubernetes command lines to harden clusters, configure pod security standards, manage secrets, restrict network policies, and detect runtime attacks with Falco.',
    highlights: [
      'Performance-based in a real live multi-node Kubernetes cluster',
      'Covers control plane hardening, RBAC, kube-bench, and Cilium policies',
      'Includes two free realistic exam simulator sessions on Killer.sh',
      'Prerequisite: Active CKA (Certified Kubernetes Administrator)'
    ],
    roiScore: '97/100',
    companySponsorshipTip: 'Crucial for enterprises running mission-critical Kubernetes workloads in production.',
    url: 'https://www.cncf.io/certification/cks/'
  },
  {
    id: 'p-eng-3',
    role: 'ENGINEERING',
    roleName: 'Security Engineering',
    cat: 'cert',
    name: 'AWS Certified Security - Specialty (SCS-C02)',
    provider: 'Amazon Web Services',
    pricingTier: '$$',
    priceEstimate: '$300 exam + $40 prep course',
    categoryName: 'Enterprise Cloud Credential',
    description: 'The definitive AWS security certification. Validates deep mastery across 5 domains: Threat Detection & Incident Response, Security Logging & Monitoring, Infrastructure Security, Identity & Access Management, and Data Protection.',
    highlights: [
      '3-hour proctored examination covering complex multi-account AWS architectures',
      'Deep dive into KMS encryption, envelope encryption, and key policies',
      'IAM permission boundaries, Service Control Policies (SCPs), and cross-account access',
      'Pairs with Adrian Cantrill\'s acclaimed video prep course'
    ],
    roiScore: '98/100',
    companySponsorshipTip: 'AWS Partner Network (APN) organizations require certified engineers to maintain discount tiers.',
    url: 'https://aws.amazon.com/certification/certified-security-specialty/'
  },
  {
    id: 'p-eng-4',
    role: 'ENGINEERING',
    roleName: 'Security Engineering',
    cat: 'cert',
    name: 'SANS SEC540: Cloud Security and DevOps Automation',
    provider: 'SANS Institute & GIAC',
    pricingTier: '$$$$',
    priceEstimate: '~$8,900 USD',
    categoryName: 'Executive Engineering Bootcamp',
    description: 'Elite training for cloud security architects and lead DevSecOps engineers. Learn to build automated security guardrails into Terraform, cloud-native deployments, and container orchestration.',
    highlights: [
      'Associated GIAC Cloud Security Automation (GCSA) credential',
      'Covers continuous compliance monitoring, policy-as-code, and cloud posture',
      '30+ hands-on cloud automation labs across AWS and Azure',
      'Taught by principal cloud security engineers'
    ],
    roiScore: '95/100',
    companySponsorshipTip: 'High-tier corporate sponsorship standard for senior cloud security engineers.',
    url: 'https://www.sans.org/cyber-security-courses/cloud-security-devops-automation/'
  },
  {
    id: 'p-eng-5',
    role: 'ENGINEERING',
    roleName: 'Security Engineering',
    cat: 'platform',
    name: 'KodeKloud Pro DevOps & Cloud Security Labs',
    provider: 'KodeKloud',
    pricingTier: '$',
    priceEstimate: '$29/mo or $228/yr',
    categoryName: 'Interactive Cloud Sandbox Platform',
    description: 'Instant browser-based terminal access to real Docker, Kubernetes, Terraform, Ansible, and cloud infrastructure environments with automated grading and practice challenges.',
    highlights: [
      'No local setup or cloud credit card required',
      'Comprehensive hands-on labs for CKA, CKS, and Terraform Associate',
      'Real-world mock exam simulators with step-by-step scoring',
      'Extremely economical subscription for continuous cloud skill sharpening'
    ],
    roiScore: '92/100',
    companySponsorshipTip: 'Very low friction expense for continuous DevOps and security skill building.',
    url: 'https://kodekloud.com/pricing'
  },
  {
    id: 'p-eng-6',
    role: 'ENGINEERING',
    roleName: 'Security Engineering',
    cat: 'cert',
    name: 'HashiCorp Certified: Terraform Associate (003)',
    provider: 'HashiCorp',
    pricingTier: '$',
    priceEstimate: '$70.50 USD exam fee',
    categoryName: 'Infrastructure as Code Security Standard',
    description: 'Validates basic concepts, skills, and understanding of open-source HashiCorp Terraform. Essential for implementing security-as-code, policy-as-code guardrails, and automated secure infrastructure deployments.',
    highlights: [
      'Industry-standard credential for modern Cloud & Platform Engineers',
      'Covers Terraform CLI, modules, state management, and Sentinel policies',
      'Extremely cost-effective certification with immediate high industry demand',
      'Directly complements AWS and Kubernetes cloud engineering credentials'
    ],
    roiScore: '96/100',
    companySponsorshipTip: 'Virtually 100% approval rate by engineering teams transitioning to automated cloud IaC.',
    url: 'https://www.hashicorp.com/certification/terraform-associate'
  },
  {
    id: 'p-eng-7',
    role: 'ENGINEERING',
    roleName: 'Security Engineering',
    cat: 'cert',
    name: 'ISC² CCSP (Certified Cloud Security Professional)',
    provider: 'ISC²',
    pricingTier: '$$$',
    priceEstimate: '$599 USD exam',
    categoryName: 'Vendor-Neutral Cloud Security Standard',
    description: 'The highest-ranked vendor-neutral cloud security credential globally. Co-developed by ISC² and the Cloud Security Alliance (CSA). Validates advanced skills across Cloud Architecture, Security, Operations, and Compliance.',
    highlights: [
      'Global gold standard covering AWS, Azure, GCP, and private cloud architecture',
      'Domains: Cloud Concepts, Data Security, Infrastructure, App Security, & Compliance',
      'Mandatory qualification for Senior Cloud Security Architects and CISOs',
      'Qualifies under DoD 8570/8140 Information Assurance Management (IAM Level III)'
    ],
    roiScore: '99/100',
    companySponsorshipTip: 'Top choice corporate sponsorship program for cloud migration and enterprise security.',
    url: 'https://www.isc2.org/certifications/ccsp'
  },
  {
    id: 'p-eng-8',
    role: 'ENGINEERING',
    roleName: 'Security Engineering',
    cat: 'tool',
    name: 'Snyk Pro Cloud-Native Application Security Platform',
    provider: 'Snyk',
    pricingTier: '$$',
    priceEstimate: '$25 – $98 / dev / mo',
    categoryName: 'Developer Security & SCA Software',
    description: 'Automates open-source dependency scanning (SCA), code analysis (SAST), container vulnerability detection, and Infrastructure as Code (IaC) drift right inside GitHub pull requests and developer IDEs.',
    highlights: [
      'Instant automated pull request fix PRs for vulnerable dependencies',
      'Scans Terraform, Kubernetes YAML, and Dockerfiles for misconfigurations',
      'Direct integration with VS Code, IntelliJ, GitHub Actions, and AWS ECR',
      'Industry-leading enterprise DevSecOps adoption'
    ],
    roiScore: '95/100',
    companySponsorshipTip: 'Standard engineering department tooling budget line item.',
    url: 'https://snyk.io/plans/'
  },

  {
    id: 'p-grc-1',
    role: 'GRC',
    roleName: 'Governance & GRC',
    cat: 'cert',
    name: 'ISACA CISA (Certified Information Systems Auditor)',
    provider: 'ISACA',
    pricingTier: '$$$',
    priceEstimate: '$760 exam + $299 QAE Database',
    categoryName: 'Global Audit Standard',
    description: 'The world-renowned gold standard for information systems audit, control, and assurance professionals. Essential for IT auditors, compliance managers, and external security assessment leads.',
    highlights: [
      'The #1 prerequisite listed by Big 4 accounting and risk advisory firms',
      'Covers Information System Auditing, IT Governance, Asset Protection, and Resilience',
      'ISACA QAE (Questions, Answers & Explanations) database is mandatory for preparation',
      'Substantial salary premium in corporate governance and enterprise risk'
    ],
    roiScore: '99/100',
    companySponsorshipTip: 'Universally approved for corporate reimbursement by internal audit and risk departments.',
    url: 'https://www.isaca.org/credentialing/cisa'
  },
  {
    id: 'p-grc-2',
    role: 'GRC',
    roleName: 'Governance & GRC',
    cat: 'cert',
    name: 'ISC² CISSP (Certified Information Systems Security Professional)',
    provider: 'ISC²',
    pricingTier: '$$$',
    priceEstimate: '$749 USD exam',
    categoryName: 'Executive Security Credential',
    description: 'The most globally requested senior information security credential. Proves advanced technical and managerial competence to design, engineer, and implement an overall enterprise information security posture.',
    highlights: [
      'Covers 8 critical security domains across technical, legal, and operational areas',
      'Recognized by governments, defense agencies, and Fortune 500 enterprises',
      'Requires 5 years of verified security experience (or 4 with degree/cert waiver)',
      'The definitive benchmark for Chief Information Security Officers (CISOs)'
    ],
    roiScore: '100/100',
    companySponsorshipTip: 'The most commonly employer-funded cybersecurity certification in history.',
    url: 'https://www.isc2.org/certifications/cissp'
  },
  {
    id: 'p-grc-3',
    role: 'GRC',
    roleName: 'Governance & GRC',
    cat: 'cert',
    name: 'ISACA CRISC (Certified in Risk and Information Systems Control)',
    provider: 'ISACA',
    pricingTier: '$$$',
    priceEstimate: '$760 exam + $299 QAE',
    categoryName: 'Enterprise Risk Management',
    description: 'Validates experience in enterprise cybersecurity risk management, risk response planning, threat evaluation, control monitoring, and regulatory reporting.',
    highlights: [
      'Covers Governance, Risk Assessment, Risk Response, and Information Technology Monitoring',
      'Connects technical cybersecurity metrics with board-level business objectives',
      'High demand among enterprise banking, healthcare, and insurance organizations',
      'Pairs with official ISACA online study modules'
    ],
    roiScore: '95/100',
    companySponsorshipTip: 'Ideal for security analysts transitioning into risk committee and advisory roles.',
    url: 'https://www.isaca.org/credentialing/crisc'
  },
  {
    id: 'p-grc-4',
    role: 'GRC',
    roleName: 'Governance & GRC',
    cat: 'cert',
    name: 'IAPP CIPP/E (Certified Information Privacy Professional/Europe)',
    provider: 'IAPP',
    pricingTier: '$$',
    priceEstimate: '$550 USD exam',
    categoryName: 'Data Privacy & Legal Compliance',
    description: 'The global standard certification for privacy professionals navigating European and international data protection laws, GDPR requirements, cross-border data transfer rules, and Data Protection Officer (DPO) duties.',
    highlights: [
      'Essential for organizations collecting user data in Europe or global cloud environments',
      'Covers European data protection authorities, legal bases for processing, and breach notification',
      'High demand across SaaS platforms, fintech, and multinational organizations',
      'Validates compliance with strict privacy-by-design engineering frameworks'
    ],
    roiScore: '94/100',
    companySponsorshipTip: 'Frequently funded by corporate legal and compliance teams to satisfy GDPR DPO requirements.',
    url: 'https://iapp.org/certify/cippe/'
  },
  {
    id: 'p-grc-5',
    role: 'GRC',
    roleName: 'Governance & GRC',
    cat: 'course',
    name: 'SANS MGT512: Security Leadership Essentials for Managers',
    provider: 'SANS Institute & GIAC',
    pricingTier: '$$$$',
    priceEstimate: '~$8,900 USD',
    categoryName: 'Leadership & Executive Training',
    description: 'Empowers security leaders to build strategic cybersecurity programs, manage budget allocation, recruit talent, present to boards, and enforce organizational policy.',
    highlights: [
      'Leads to the GIAC Certified Security Leadership (GSLC) credential',
      'Learn how to translate technical vulnerability scans into business risk',
      'Enterprise security architecture and incident management strategies',
      'Includes case study exercises from Fortune 100 enterprise environments'
    ],
    roiScore: '93/100',
    companySponsorshipTip: 'Executive development budget line item for incoming managers, directors, and CISOs.',
    url: 'https://www.sans.org/cyber-security-courses/security-leadership-essentials-for-managers/'
  },
  {
    id: 'p-grc-6',
    role: 'GRC',
    roleName: 'Governance & GRC',
    cat: 'cert',
    name: 'ISACA CISM (Certified Information Security Manager)',
    provider: 'ISACA',
    pricingTier: '$$$',
    priceEstimate: '$760 USD exam fee',
    categoryName: 'Enterprise Security Management Standard',
    description: 'Specifically targets management-level information security responsibilities. Focuses on information security governance, incident management, risk management, and security program development.',
    highlights: [
      'The #1 requested credential for aspiring and current Chief Information Security Officers',
      'Covers Security Governance, Risk Management, Security Program, & Incident Management',
      'Recognized by global governments and corporate boards of directors',
      'Pairs with official ISACA interactive QAE prep database'
    ],
    roiScore: '99/100',
    companySponsorshipTip: 'Universally approved for senior security engineers transitioning to leadership.',
    url: 'https://www.isaca.org/credentialing/cism'
  },
  {
    id: 'p-grc-7',
    role: 'GRC',
    roleName: 'Governance & GRC',
    cat: 'cert',
    name: 'Cloud Security Alliance: Certificate of Cloud Security Knowledge (CCSK v5)',
    provider: 'Cloud Security Alliance (CSA)',
    pricingTier: '$$',
    priceEstimate: '$395 USD exam fee',
    categoryName: 'Cloud Governance & Audit Credential',
    description: 'Widely recognized as the mother of all cloud security certifications. Covers cloud architecture, governance, legal issues, compliance, audit, and the CSA Cloud Controls Matrix (CCM).',
    highlights: [
      'Open-book online examination with 2 attempts included',
      'Comprehensive coverage of CSA Security Guidance v5 and ENISA recommendations',
      'Essential for IT auditors, compliance leads, and cloud procurement specialists',
      'Direct stepping-stone toward ISC² CCSP certification'
    ],
    roiScore: '95/100',
    companySponsorshipTip: 'Very high return on investment with reasonable exam fee easily covered by training budgets.',
    url: 'https://cloudsecurityalliance.org/education/ccsk'
  },
  {
    id: 'p-grc-8',
    role: 'GRC',
    roleName: 'Governance & GRC',
    cat: 'tool',
    name: 'ComplianceForge Secure Controls Framework (SCF) Enterprise Kit',
    provider: 'ComplianceForge',
    pricingTier: '$$$',
    priceEstimate: '~$1,200 USD',
    categoryName: 'Enterprise Policy & Compliance Documentation Kit',
    description: 'Production-ready, customizable cybersecurity documentation, policies, standards, and procedures cross-mapped against NIST CSF, ISO 27001, SOC 2, HIPAA, PCI DSS, and GDPR.',
    highlights: [
      'Over 100+ professionally drafted Word/Excel policies and procedures ready for audit',
      'Complete mapping across 1,000+ controls in the Secure Controls Framework (SCF)',
      'Saves compliance teams 6-12 months of manual document drafting',
      'Used by enterprise compliance officers and cybersecurity consulting practices'
    ],
    roiScore: '96/100',
    companySponsorshipTip: 'Significant cost saver for companies undergoing SOC 2 or ISO 27001 audit readiness.',
    url: 'https://complianceforge.com/'
  },

  {
    id: 'p-ai-1',
    role: 'AI_SECURITY',
    roleName: 'AI & Emerging Security',
    cat: 'cert',
    name: 'SANS SEC595: Applied Data Science and AI/ML for Cybersecurity',
    provider: 'SANS Institute & GIAC',
    pricingTier: '$$$$',
    priceEstimate: '~$8,900 USD',
    categoryName: 'Frontier AI Security Bootcamp',
    description: 'Practical data science and machine learning for security practitioners. Learn to train anomaly detection neural networks, evaluate foundation model robustness, and counter adversarial machine learning attacks.',
    highlights: [
      'First dedicated hands-on machine learning security bootcamp from SANS',
      'Hands-on PyTorch, Scikit-learn, and transformer security architectures',
      'Detecting prompt injections, model extraction, and data poisoning attacks',
      'Eligible for GIAC Artificial Intelligence Security certification'
    ],
    roiScore: '96/100',
    companySponsorshipTip: 'Critical for organizations deploying internal generative AI models and custom LLMs.',
    url: 'https://www.sans.org/cyber-security-courses/applied-data-science-machine-learning/'
  },
  {
    id: 'p-ai-2',
    role: 'AI_SECURITY',
    roleName: 'AI & Emerging Security',
    cat: 'course',
    name: 'Securing Generative AI Systems (Practical DevSecOps)',
    provider: 'Practical DevSecOps',
    pricingTier: '$$$',
    priceEstimate: '$799 USD',
    categoryName: 'GenAI Security Engineering Course',
    description: 'Hands-on practical curriculum focusing on securing RAG pipelines, deploying guardrails against prompt injection, model alignment verification, and protecting sensitive corporate data inside vector databases.',
    highlights: [
      'Practical labs testing live vulnerabilities against LangChain and LlamaIndex',
      'Preventing indirect prompt injections through external web data ingestion',
      'Securing vector database access controls and embedding confidentiality',
      'Includes industry-recognized certificate of completion'
    ],
    roiScore: '95/100',
    companySponsorshipTip: 'Immediate application for companies building customer-facing AI agents and copilot tools.',
    url: 'https://www.practical-devsecops.com/securing-generative-ai-systems/'
  },
  {
    id: 'p-ai-3',
    role: 'AI_SECURITY',
    roleName: 'AI & Emerging Security',
    cat: 'course',
    name: 'DeepLearning.AI: Generative AI Red Teaming Specialization',
    provider: 'Coursera & DeepLearning.AI',
    pricingTier: '$',
    priceEstimate: '$49 / month',
    categoryName: 'Online Practical Specialization',
    description: 'Created by leading AI researchers. Learn automated adversarial prompt generation, safety benchmark evaluation, and techniques used by frontier AI labs to discover model failure modes.',
    highlights: [
      'Interactive Jupyter Notebook coding exercises in Python',
      'Hands-on red teaming against open-source and commercial LLM APIs',
      'Techniques for measuring hallucination rates and jailbreak susceptibility',
      'Self-paced, accessible monthly subscription'
    ],
    roiScore: '92/100',
    companySponsorshipTip: 'Low barrier monthly subscription that provides instant foundational skills in AI red teaming.',
    url: 'https://learn.deeplearning.ai/courses/red-teaming-llm-applications'
  },
  {
    id: 'p-ai-4',
    role: 'AI_SECURITY',
    roleName: 'AI & Emerging Security',
    cat: 'tool',
    name: 'Lakera Guard Enterprise AI Defense Suite',
    provider: 'Lakera AI',
    pricingTier: '$$$',
    priceEstimate: 'Developer to Enterprise Tier (~$350/mo)',
    categoryName: 'Production AI Firewall & Defense Platform',
    description: 'Real-time API gateway that intercepts and blocks prompt injections, jailbreaks, data leakage, and toxic outputs before they reach your enterprise LLM or your end users.',
    highlights: [
      'Single API call latency of under 50ms for real-time inference protection',
      'Continuous threat database updated against thousands of newly discovered jailbreaks',
      'Prevents automated model extraction and PII data leakage',
      'Enterprise dashboard monitoring attacks across all connected AI applications'
    ],
    roiScore: '94/100',
    companySponsorshipTip: 'Essential SaaS infrastructure protection for any production generative AI application.',
    url: 'https://platform.lakera.ai'
  },
  {
    id: 'p-ai-5',
    role: 'AI_SECURITY',
    roleName: 'AI & Emerging Security',
    cat: 'tool',
    name: 'Prompt Security Enterprise Generative AI Shield',
    provider: 'Prompt Security',
    pricingTier: '$$$',
    priceEstimate: 'Enterprise Tier / Flexible Pilot',
    categoryName: 'Enterprise GenAI Security Software',
    description: 'Complete visibility and governance over all GenAI tool usage in the enterprise. Inspects prompts for confidential source code, customer PII, secret keys, and blocks shadow AI usage in employee browsers.',
    highlights: [
      'Inspects employee browser interactions with ChatGPT, Claude, Gemini, and Copilot',
      'Real-time PII and API secret token redaction before prompts leave the perimeter',
      'Prevents intellectual property leaks into third-party foundation models',
      'Seamless deployment with zero network latency degradation'
    ],
    roiScore: '95/100',
    companySponsorshipTip: 'Critical for corporate compliance with enterprise AI acceptable use policies.',
    url: 'https://www.prompt.security/'
  },
  {
    id: 'p-ai-6',
    role: 'AI_SECURITY',
    roleName: 'AI & Emerging Security',
    cat: 'platform',
    name: 'Giskard AI Security Testing & Automated Red Teaming Suite',
    provider: 'Giskard AI',
    pricingTier: '$$',
    priceEstimate: 'Developer ($0) to Enterprise Cloud ($499/mo)',
    categoryName: 'Automated LLM Security Testing Platform',
    description: 'The automated quality and security scanner for LLM applications. Automatically generates adversarial test cases, probes for prompt injection vulnerabilities, hallucination rates, and model bias.',
    highlights: [
      'Automated scan for prompt injection, harmful content, and data leakage',
      'CI/CD test automation for ML models and LLM agents before production deployment',
      'Visual test reports mapping to OWASP Top 10 for Large Language Models',
      'Supported by the European AI safety research community'
    ],
    roiScore: '96/100',
    companySponsorshipTip: 'Automates manual QA and security verification for all enterprise AI engineering teams.',
    url: 'https://www.giskard.ai/'
  },
  {
    id: 'p-ai-7',
    role: 'AI_SECURITY',
    roleName: 'AI & Emerging Security',
    cat: 'tool',
    name: 'HiddenLayer Machine Learning Security Platform (MLSecOps)',
    provider: 'HiddenLayer',
    pricingTier: '$$$$',
    priceEstimate: 'Enterprise Custom Pricing',
    categoryName: 'MLSecOps Threat Detection Platform',
    description: 'Recognized as RSA Conference Most Innovative Startup. Provides non-invasive real-time security detection for ML algorithms and foundation models against adversarial evasion, inversion, and theft.',
    highlights: [
      'Machine Learning Detection & Response (MLDR) monitoring model inputs & outputs',
      'Model scanner inspecting safetensors, pickle files, and weights for backdoors',
      'Integrates directly with Databricks, AWS SageMaker, and Hugging Face pipelines',
      'Essential for organizations deploying proprietary proprietary proprietary ML models'
    ],
    roiScore: '97/100',
    companySponsorshipTip: 'Mandatory risk management requirement for enterprise machine learning operations.',
    url: 'https://hiddenlayer.com/'
  },
  {
    id: 'p-ai-8',
    role: 'AI_SECURITY',
    roleName: 'AI & Emerging Security',
    cat: 'platform',
    name: 'Bosch AIShield - AI Vulnerability Assessment & Defense',
    provider: 'Bosch AIShield',
    pricingTier: '$$$$',
    priceEstimate: 'Enterprise Tier',
    categoryName: 'AI Vulnerability Assessment API & Endpoint Defense',
    description: 'Automated security assessment engine created by Bosch engineers. Generates custom adversarial attacks tailored to your specific neural network architecture and generates automated defense patches.',
    highlights: [
      'Automated vulnerability assessment generating thousands of model-specific attacks',
      'Generates automated lightweight runtime defense models to block evasion',
      'Supports computer vision, NLP, tabular models, and frontier LLMs',
      'Direct mapping to NIST AI Risk Management Framework (RMF 1.0)'
    ],
    roiScore: '94/100',
    companySponsorshipTip: 'High-value security assessment tool for regulated automotive, medical, and financial AI.',
    url: 'https://www.boschaishield.com/'
  }
];
